# This config is a STUB! This should never be generated.
# Use the default lua config from https://github.com/hyprwm/Hyprland/blob/main/example/hyprland.lua

input {
    kb_layout = us,latam
}

$mainMod = SUPER
$terminal = kitty
$fileManager = dolphin
$menu = rofi -show run

source = ~/.config/hypr/keybindings.conf
source = ~/.config/hypr/windowrules.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/workspaces-dynamic.conf

exec-once = ~/.config/hypr/scripts/monitor-layout.sh
exec-once = ~/.config/hypr/scripts/autostart.sh
