$image = /home/yb-m/Pictures/wallpapers/black_hole_by_kurzgesagt.png

$text_color = rgba(fdd6ffFF)
$entry_background_color = rgba(18111911)
$entry_border_color = rgba(9d8b9c55)
$entry_color = rgba(fdd6ffFF)
