# Hypridle standalone
# Sin dependencias de HyDE.

general {
    lock_cmd = /home/yb-m/.config/hypr/scripts/lock.sh

    # Respetar aplicaciones e inhibidores como Modo Cafeína.
    ignore_dbus_inhibit = false
    ignore_systemd_inhibit = false

    after_sleep_cmd = /home/yb-m/.config/hypr/scripts/post-resume.sh
}

# Bajar brillo tras 60 segundos.
listener {
    timeout = 60
    on-timeout = brightnessctl -s && brightnessctl s 1%
    on-resume = brightnessctl -r
}

# Bloquear tras 120 segundos.
listener {
    timeout = 120
    on-timeout = loginctl lock-session
}

# Apagar pantallas tras 300 segundos.
listener {
    timeout = 300
    on-timeout = hyprctl dispatch 'hl.dsp.dpms("off")'
    on-resume = hyprctl dispatch 'hl.dsp.dpms("on")'
}

# Suspender tras 500 segundos.
listener {
    timeout = 500
    on-timeout = systemctl suspend
}
