workspace=1,monitor:desc:LG Display 0x07A3,default:true
workspace=2,monitor:desc:LG Display 0x07A3
workspace=3,monitor:desc:LG Display 0x07A3
workspace=4,monitor:desc:LG Display 0x07A3
workspace=5,monitor:desc:LG Display 0x07A3
workspace=6,monitor:desc:LG Display 0x07A3
workspace=7,monitor:desc:LG Display 0x07A3
workspace=8,monitor:desc:LG Display 0x07A3
workspace=9,monitor:desc:LG Display 0x07A3
workspace=10,monitor:desc:LG Display 0x07A3
